package_assets:         on          # (on, off, always)
embed_assets:           on          # (on, off, datauri)
compress_assets:        on          # (on, off)
gzip_assets:            on 

stylesheets:
  common:
    - public/stylesheets/*.css

